Repository tulios/kafkajs, pull requests merged in 2019-02, with the labels that each got.

#253 Fix consumer restart on find coordinator errors
  jest.config.js
  package.json
  src/cluster/__tests__/findGroupCoordinator.spec.js
  src/cluster/index.js
  yarn.lock
Labels: bug

#256 Crash consumer on codec not implemented error
  src/consumer/__tests__/runner.spec.js
  src/consumer/runner.js
  src/protocol/requests/fetch/fixtures/v4_response_snappy.json
  src/protocol/requests/fetch/v4/response.js
  src/protocol/requests/fetch/v4/response.spec.js
Labels: bug

#255 Add tests for compression not implemented
  src/producer/compression.spec.js
Labels: enhancement

#278 Set log level after instantiation
  docs/Configuration.md
  src/__snapshots__/index.spec.js.snap
  src/admin/__snapshots__/index.spec.js.snap
  src/consumer/__tests__/__snapshots__/logger.spec.js.snap
  src/loggers/index.js
  src/loggers/index.spec.js
  src/producer/__snapshots__/index.spec.js.snap
Labels: enhancement

#286 Document the fromBeginning option of subscribe
  docs/Consuming.md
Labels: documentation

#295 Fix propagation of custom retry configs
  src/index.js
  src/index.spec.js
Labels: bug
