Repository tulios/kafkajs, pull requests merged in 2020-03, with the labels that each got.

#655 Retry failing tests in CI
  azure-pipelines.yml
  jest.config.js
  package.json
  src/admin/__tests__/deleteTopics.spec.js
  src/admin/index.spec.js
  src/broker/__tests__/addPartitionsToTxn.spec.js
  src/broker/__tests__/deleteTopics.spec.js
  src/broker/__tests__/txnOffsetCommit.spec.js
  src/consumer/__tests__/errorRecovery.spec.js
  src/consumer/__tests__/runner.spec.js
  src/consumer/offsetManager/__tests__/initializeConsumerOffsets.spec.js
  src/producer/index.spec.js
  src/protocol/requests/addPartitionsToTxn/v0/response.spec.js
  src/protocol/requests/produce/v0/request.spec.js
  src/protocol/requests/txnOffsetCommit/v0/request.spec.js
  src/protocol/requests/txnOffsetCommit/v0/response.spec.js
  testHelpers/setup.js
  yarn.lock
Labels: enhancement

#662 Update documentation for pause/resume in the website
  docs/Consuming.md
Labels: documentation

#545 Provide the _subscribed_ topics to the protocol() function
  src/consumer/consumerGroup.js
Labels: enhancement

#666 Remove invalid topics from targetTopics on INVALID_TOPIC_EXCEPTION
  src/cluster/index.js
  src/producer/__tests__/producingToInvalidTopic.spec.js
Labels: bug
